spring:
  application:
    name: uaa‐service
  # HTTP编码配置
  http:
    encoding:
      enabled: true
      charset: utf-8
      force: true
  main:
    allow-bean-definition-overriding: true #允许bean定义覆盖
  freemarker: #
    enabled: true
    suffix: .html
    request-context-attribute: rc
    content-type: text/html
    charset: UTF-8
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false
  datasource:
    url: jdbc:mysql://182.92.131.138:3306/spring_security
    username: root
    driver-class-name: com.mysql.jdbc.Driver
server:
  port: 53020
  tomcat:
    remote_ip_header: x-forwarded-for
    protocol-header: x-forwarded-proto
  use-forward-headers: true
  servlet:
    context-path: /uaa
logging:
  level:
    org:
      springframework:
        web: info
    root: debug


  #eureka.client.serviceUrl.defaultZone = http://localhost:53000/eureka/ #eureka.instance.preferIpAddress = true
  #eureka.instance.instance‐id = ${spring.application.name}:${spring.cloud.client.ip‐ address}:${spring.application.instance_id:${server.port}} management.endpoints.web.exposure.include = refresh,health,info,env
feign:
  hystrix:
    enabled: true
  compression:
    request:
      enabled: true
      mime-types:
        - text/xml
        - application/json
        - application/xml
      min-request-size: 2048
    response:
      enabled: true